# Generated by Django 2.0.7 on 2018-09-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180901_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('n', 'Normal'), ('m', 'Medium'), ('h', 'High')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeat',
            field=models.IntegerField(choices=[('n', 'No Repeat'), ('d', 'Daily'), ('w', 'Weekly'), ('m', 'Monthly'), ('y', 'Yearly')], default='n', max_length=1),
        ),
    ]
